import React, { useState } from 'react';
import { useTheme } from '../ThemeContext.jsx';

/**
 * RiskAnalysisReport Component
 * Displays a professional risk analysis report generated by AI
 * Suitable for printing and sharing with risk officers
 */
const RiskAnalysisReport = ({ report }) => {
  const { isDarkMode } = useTheme();
  const [expandedAnalyses, setExpandedAnalyses] = useState(new Set());

  if (!report) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-secondary)' }}>
        No report data available
      </div>
    );
  }

  const { summary, analyses, executiveSummary, impactedProducts, generatedAt } = report;

  const toggleAnalysis = (symbol) => {
    const newExpanded = new Set(expandedAnalyses);
    if (newExpanded.has(symbol)) {
      newExpanded.delete(symbol);
    } else {
      newExpanded.add(symbol);
    }
    setExpandedAnalyses(newExpanded);
  };

  const getRiskBadgeStyle = (riskLevel) => {
    const baseStyle = {
      display: 'inline-block',
      padding: '0.25rem 0.75rem',
      borderRadius: '12px',
      fontSize: '0.75rem',
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: '0.5px'
    };

    switch (riskLevel) {
      case 'critical':
        return {
          ...baseStyle,
          background: isDarkMode ? 'rgba(239, 68, 68, 0.2)' : '#fecaca',
          color: isDarkMode ? '#fca5a5' : '#991b1b',
          border: isDarkMode ? '1px solid rgba(239, 68, 68, 0.3)' : 'none'
        };
      case 'high':
        return {
          ...baseStyle,
          background: isDarkMode ? 'rgba(249, 115, 22, 0.2)' : '#fed7aa',
          color: isDarkMode ? '#fdba74' : '#9a3412',
          border: isDarkMode ? '1px solid rgba(249, 115, 22, 0.3)' : 'none'
        };
      case 'moderate':
        return {
          ...baseStyle,
          background: isDarkMode ? 'rgba(234, 179, 8, 0.2)' : '#fef08a',
          color: isDarkMode ? '#fde047' : '#854d0e',
          border: isDarkMode ? '1px solid rgba(234, 179, 8, 0.3)' : 'none'
        };
      default:
        return {
          ...baseStyle,
          background: isDarkMode ? 'rgba(156, 163, 175, 0.2)' : '#d1d5db',
          color: isDarkMode ? '#9ca3af' : '#374151',
          border: isDarkMode ? '1px solid rgba(156, 163, 175, 0.3)' : 'none'
        };
    }
  };

  const formatDate = (date) => {
    return new Date(date).toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <div style={{
      fontFamily: '"Inter", -apple-system, system-ui, sans-serif',
      color: isDarkMode ? '#e5e7eb' : '#1f2937',
      maxWidth: '1000px',
      margin: '0 auto',
      padding: '2rem',
      background: isDarkMode ? '#1f2937' : '#ffffff'
    }}>
      {/* Report Header */}
      <div style={{
        borderBottom: `3px solid ${isDarkMode ? '#374151' : '#e5e7eb'}`,
        paddingBottom: '2rem',
        marginBottom: '2rem'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start' }}>
          <div>
            <h1 style={{
              margin: '0 0 0.5rem 0',
              fontSize: '2rem',
              fontWeight: '700',
              color: '#ef4444'
            }}>
              Portfolio Risk Analysis Report
            </h1>
            <p style={{
              margin: 0,
              fontSize: '1rem',
              color: isDarkMode ? '#9ca3af' : '#6b7280',
              fontWeight: '500'
            }}>
              Structured Products - Barrier Risk Assessment
            </p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{
              margin: '0 0 0.25rem 0',
              fontSize: '0.875rem',
              color: isDarkMode ? '#9ca3af' : '#6b7280'
            }}>
              Generated: {formatDate(generatedAt)}
            </p>
            <p style={{
              margin: 0,
              fontSize: '0.75rem',
              color: isDarkMode ? '#6b7280' : '#9ca3af',
              fontStyle: 'italic'
            }}>
              Amberlake Analysis
            </p>
          </div>
        </div>
      </div>

      {/* Summary Cards */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
        gap: '1rem',
        marginBottom: '2rem'
      }}>
        <div style={{
          background: isDarkMode ? '#374151' : '#f9fafb',
          borderRadius: '12px',
          padding: '1rem',
          border: `1px solid ${isDarkMode ? '#4b5563' : '#e5e7eb'}`
        }}>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#9ca3af' : '#6b7280',
            marginBottom: '0.25rem',
            textTransform: 'uppercase',
            fontWeight: '600',
            letterSpacing: '0.5px'
          }}>
            At Risk
          </div>
          <div style={{
            fontSize: '1.75rem',
            fontWeight: '700',
            color: '#ef4444'
          }}>
            {summary.uniqueUnderlyings}
          </div>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#6b7280' : '#9ca3af'
          }}>
            Unique underlyings
          </div>
        </div>

        <div style={{
          background: isDarkMode ? '#374151' : '#f9fafb',
          borderRadius: '12px',
          padding: '1rem',
          border: `1px solid ${isDarkMode ? '#4b5563' : '#e5e7eb'}`
        }}>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#9ca3af' : '#6b7280',
            marginBottom: '0.25rem',
            textTransform: 'uppercase',
            fontWeight: '600',
            letterSpacing: '0.5px'
          }}>
            Critical
          </div>
          <div style={{
            fontSize: '1.75rem',
            fontWeight: '700',
            color: '#dc2626'
          }}>
            {summary.criticalRisk}
          </div>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#6b7280' : '#9ca3af'
          }}>
            &gt;5% below barrier
          </div>
        </div>

        <div style={{
          background: isDarkMode ? '#374151' : '#f9fafb',
          borderRadius: '12px',
          padding: '1rem',
          border: `1px solid ${isDarkMode ? '#4b5563' : '#e5e7eb'}`
        }}>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#9ca3af' : '#6b7280',
            marginBottom: '0.25rem',
            textTransform: 'uppercase',
            fontWeight: '600',
            letterSpacing: '0.5px'
          }}>
            Avg Distance
          </div>
          <div style={{
            fontSize: '1.75rem',
            fontWeight: '700',
            color: summary.averageDistanceToBarrier >= 0 ? '#10b981' : '#ef4444'
          }}>
            {summary.averageDistanceToBarrier >= 0 ? '+' : ''}{summary.averageDistanceToBarrier.toFixed(1)}%
          </div>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#6b7280' : '#9ca3af'
          }}>
            To barrier
          </div>
        </div>

        <div style={{
          background: isDarkMode ? '#374151' : '#f9fafb',
          borderRadius: '12px',
          padding: '1rem',
          border: `1px solid ${isDarkMode ? '#4b5563' : '#e5e7eb'}`
        }}>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#9ca3af' : '#6b7280',
            marginBottom: '0.25rem',
            textTransform: 'uppercase',
            fontWeight: '600',
            letterSpacing: '0.5px'
          }}>
            Avg Time
          </div>
          <div style={{
            fontSize: '1.75rem',
            fontWeight: '700',
            color: isDarkMode ? '#e5e7eb' : '#1f2937'
          }}>
            {Math.round(summary.averageDaysRemaining)}
          </div>
          <div style={{
            fontSize: '0.75rem',
            color: isDarkMode ? '#6b7280' : '#9ca3af'
          }}>
            Days remaining
          </div>
        </div>
      </div>

      {/* Executive Summary */}
      <div style={{
        background: isDarkMode ? 'rgba(245, 158, 11, 0.1)' : '#fffbeb',
        borderLeft: `4px solid ${isDarkMode ? '#fbbf24' : '#f59e0b'}`,
        borderRadius: '8px',
        padding: '1.5rem',
        marginBottom: '2rem',
        border: isDarkMode ? '1px solid rgba(245, 158, 11, 0.2)' : 'none',
        borderLeftWidth: '4px',
        borderLeftStyle: 'solid'
      }}>
        <h2 style={{
          margin: '0 0 1rem 0',
          fontSize: '1.25rem',
          fontWeight: '700',
          color: isDarkMode ? '#fbbf24' : '#f59e0b',
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem'
        }}>
          <span>📊</span> Executive Summary
        </h2>
        <div style={{
          fontSize: '0.95rem',
          lineHeight: '1.6',
          color: isDarkMode ? '#e5e7eb' : '#374151',
          whiteSpace: 'pre-wrap'
        }}>
          {executiveSummary}
        </div>
      </div>

      {/* Impacted Products */}
      {impactedProducts && impactedProducts.length > 0 && (
        <div style={{
          background: isDarkMode ? 'rgba(59, 130, 246, 0.1)' : '#eff6ff',
          borderLeft: `4px solid ${isDarkMode ? '#60a5fa' : '#3b82f6'}`,
          borderRadius: '8px',
          padding: '1.5rem',
          marginBottom: '2rem',
          border: isDarkMode ? '1px solid rgba(59, 130, 246, 0.2)' : 'none',
          borderLeftWidth: '4px',
          borderLeftStyle: 'solid'
        }}>
          <h2 style={{
            margin: '0 0 1rem 0',
            fontSize: '1.25rem',
            fontWeight: '700',
            color: isDarkMode ? '#60a5fa' : '#3b82f6',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem'
          }}>
            <span>📋</span> Impacted Products ({impactedProducts.length})
          </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {impactedProducts && impactedProducts.map((product, idx) => (
            <div
              key={product.productId}
              style={{
                background: isDarkMode ? '#1f2937' : '#ffffff',
                border: `1px solid ${isDarkMode ? '#374151' : '#e5e7eb'}`,
                borderRadius: '8px',
                padding: '1rem'
              }}
            >
              <div style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'start',
                marginBottom: '0.75rem'
              }}>
                <div style={{ flex: 1 }}>
                  <div style={{
                    fontWeight: '700',
                    fontSize: '1rem',
                    color: isDarkMode ? '#e5e7eb' : '#1f2937',
                    marginBottom: '0.25rem'
                  }}>
                    {product.productTitle}
                  </div>
                  <div style={{
                    fontSize: '0.75rem',
                    color: isDarkMode ? '#6b7280' : '#9ca3af',
                    fontFamily: 'monospace'
                  }}>
                    {product.productIsin}
                  </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{
                    fontSize: '0.75rem',
                    color: isDarkMode ? '#9ca3af' : '#6b7280',
                    marginBottom: '0.25rem'
                  }}>
                    Worst Distance
                  </div>
                  <div style={{
                    fontSize: '1.125rem',
                    fontWeight: '700',
                    color: product.worstDistance >= 0 ? '#10b981' : '#ef4444'
                  }}>
                    {product.worstDistance >= 0 ? '+' : ''}{product.worstDistance.toFixed(1)}%
                  </div>
                </div>
              </div>

              <div style={{
                fontSize: '0.75rem',
                color: isDarkMode ? '#9ca3af' : '#6b7280',
                marginBottom: '0.5rem',
                fontWeight: '600',
                textTransform: 'uppercase',
                letterSpacing: '0.5px'
              }}>
                At-Risk Underlyings ({product.atRiskUnderlyings.length})
              </div>

              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {product.atRiskUnderlyings.map((underlying, uIdx) => (
                  <div
                    key={uIdx}
                    style={{
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: '0.5rem',
                      padding: '0.375rem 0.75rem',
                      background: isDarkMode ? '#374151' : '#f9fafb',
                      borderRadius: '6px',
                      fontSize: '0.85rem'
                    }}
                  >
                    <span style={{
                      fontWeight: '600',
                      color: isDarkMode ? '#e5e7eb' : '#1f2937'
                    }}>
                      {underlying.symbol}
                    </span>
                    <span style={{
                      color: underlying.distanceToBarrier >= 0 ? '#10b981' : '#ef4444',
                      fontWeight: '600'
                    }}>
                      {underlying.distanceToBarrier >= 0 ? '+' : ''}{underlying.distanceToBarrier.toFixed(1)}%
                    </span>
                    <span style={getRiskBadgeStyle(underlying.riskLevel)}>
                      {underlying.riskLevel}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
        </div>
      )}

      {/* Individual Stock Analyses */}
      <div>
        <h2 style={{
          margin: '0 0 1.5rem 0',
          fontSize: '1.5rem',
          fontWeight: '700',
          color: isDarkMode ? '#e5e7eb' : '#1f2937',
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem'
        }}>
          <span>🔍</span> Detailed Analysis by Underlying
        </h2>

        {analyses.map((analysis, index) => {
          const isExpanded = expandedAnalyses.has(analysis.symbol);

          return (
            <div
              key={analysis.symbol}
              style={{
                background: isDarkMode ? '#374151' : '#ffffff',
                border: `1px solid ${isDarkMode ? '#4b5563' : '#e5e7eb'}`,
                borderRadius: '12px',
                marginBottom: '1rem',
                overflow: 'hidden'
              }}
            >
              {/* Header - Clickable to expand/collapse */}
              <div
                onClick={() => toggleAnalysis(analysis.symbol)}
                style={{
                  padding: '1.25rem',
                  cursor: 'pointer',
                  background: isDarkMode ? '#2d3748' : '#f9fafb',
                  borderBottom: isExpanded ? `1px solid ${isDarkMode ? '#4b5563' : '#e5e7eb'}` : 'none',
                  transition: 'background 0.2s',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center'
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = isDarkMode ? '#1f2937' : '#f3f4f6';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = isDarkMode ? '#2d3748' : '#f9fafb';
                }}
              >
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '0.5rem' }}>
                    <h3 style={{
                      margin: 0,
                      fontSize: '1.125rem',
                      fontWeight: '700',
                      color: isDarkMode ? '#e5e7eb' : '#1f2937'
                    }}>
                      {analysis.symbol}
                    </h3>
                    <span style={getRiskBadgeStyle(analysis.riskLevel)}>
                      {analysis.riskLevel} risk
                    </span>
                  </div>
                  <p style={{
                    margin: '0 0 0.5rem 0',
                    fontSize: '0.9rem',
                    color: isDarkMode ? '#9ca3af' : '#6b7280'
                  }}>
                    {analysis.companyName}
                  </p>
                  <div style={{
                    display: 'flex',
                    gap: '1.5rem',
                    fontSize: '0.85rem',
                    color: isDarkMode ? '#6b7280' : '#9ca3af'
                  }}>
                    <span>
                      Distance: <strong style={{
                        color: analysis.distanceToBarrier >= 0 ? '#10b981' : '#ef4444'
                      }}>
                        {analysis.distanceToBarrier >= 0 ? '+' : ''}{analysis.distanceToBarrier.toFixed(1)}%
                      </strong>
                    </span>
                    <span>
                      Days: <strong style={{ color: isDarkMode ? '#d1d5db' : '#374151' }}>
                        {analysis.daysRemaining}
                      </strong>
                    </span>
                    <span>
                      Products: <strong style={{ color: isDarkMode ? '#d1d5db' : '#374151' }}>
                        {analysis.products?.length || 0}
                      </strong>
                    </span>
                  </div>
                </div>
                <div style={{
                  fontSize: '1.5rem',
                  color: isDarkMode ? '#9ca3af' : '#6b7280',
                  transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)',
                  transition: 'transform 0.2s'
                }}>
                  ▼
                </div>
              </div>

              {/* Content - Expandable */}
              {isExpanded && (
                <div style={{ padding: '1.5rem' }}>
                  {/* Key Metrics */}
                  <div style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                    gap: '1rem',
                    marginBottom: '1.5rem',
                    padding: '1rem',
                    background: isDarkMode ? '#1f2937' : '#f9fafb',
                    borderRadius: '8px'
                  }}>
                    <div>
                      <div style={{
                        fontSize: '0.75rem',
                        color: isDarkMode ? '#9ca3af' : '#6b7280',
                        marginBottom: '0.25rem'
                      }}>
                        Current Price
                      </div>
                      <div style={{
                        fontSize: '1.125rem',
                        fontWeight: '600',
                        color: isDarkMode ? '#e5e7eb' : '#1f2937'
                      }}>
                        {analysis.currentPrice.toFixed(2)}
                      </div>
                    </div>
                    <div>
                      <div style={{
                        fontSize: '0.75rem',
                        color: isDarkMode ? '#9ca3af' : '#6b7280',
                        marginBottom: '0.25rem'
                      }}>
                        Barrier Price
                      </div>
                      <div style={{
                        fontSize: '1.125rem',
                        fontWeight: '600',
                        color: '#ef4444'
                      }}>
                        {analysis.barrierPrice.toFixed(2)}
                      </div>
                    </div>
                    <div>
                      <div style={{
                        fontSize: '0.75rem',
                        color: isDarkMode ? '#9ca3af' : '#6b7280',
                        marginBottom: '0.25rem'
                      }}>
                        Performance
                      </div>
                      <div style={{
                        fontSize: '1.125rem',
                        fontWeight: '600',
                        color: analysis.performance >= 0 ? '#10b981' : '#ef4444'
                      }}>
                        {analysis.performance >= 0 ? '+' : ''}{analysis.performance.toFixed(2)}%
                      </div>
                    </div>
                  </div>

                  {/* AI Analysis */}
                  <div style={{
                    background: isDarkMode ? '#1e293b' : '#ffffff',
                    border: `1px solid ${isDarkMode ? '#334155' : '#e5e7eb'}`,
                    borderRadius: '8px',
                    padding: '1.5rem',
                    marginBottom: '1rem'
                  }}>
                    <h4 style={{
                      margin: '0 0 1rem 0',
                      fontSize: '1rem',
                      fontWeight: '600',
                      color: '#8b5cf6',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.5rem'
                    }}>
                      <span>🤖</span> Amberlake Comment
                    </h4>
                    <div style={{
                      fontSize: '0.925rem',
                      lineHeight: '1.7',
                      color: isDarkMode ? '#d1d5db' : '#374151',
                      whiteSpace: 'pre-wrap'
                    }}>
                      {analysis.analysis}
                    </div>
                  </div>

                  {/* Affected Products */}
                  {analysis.products && analysis.products.length > 0 && (
                    <div>
                      <h4 style={{
                        margin: '0 0 0.75rem 0',
                        fontSize: '0.9rem',
                        fontWeight: '600',
                        color: isDarkMode ? '#9ca3af' : '#6b7280'
                      }}>
                        Affected Products ({analysis.products.length})
                      </h4>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                        {analysis.products.map((product, idx) => (
                          <div
                            key={idx}
                            style={{
                              padding: '0.75rem',
                              background: isDarkMode ? '#1f2937' : '#f9fafb',
                              borderRadius: '6px',
                              fontSize: '0.85rem',
                              display: 'flex',
                              justifyContent: 'space-between',
                              alignItems: 'center'
                            }}
                          >
                            <div>
                              <div style={{
                                fontWeight: '600',
                                color: isDarkMode ? '#e5e7eb' : '#1f2937',
                                marginBottom: '0.25rem'
                              }}>
                                {product.productTitle}
                              </div>
                              <div style={{
                                fontSize: '0.75rem',
                                color: isDarkMode ? '#6b7280' : '#9ca3af',
                                fontFamily: 'monospace'
                              }}>
                                {product.productIsin}
                              </div>
                            </div>
                            <div style={{ textAlign: 'right', fontSize: '0.8rem' }}>
                              <div style={{ color: product.distanceToBarrier >= 0 ? '#10b981' : '#ef4444', fontWeight: '600' }}>
                                {product.distanceToBarrier >= 0 ? '+' : ''}{product.distanceToBarrier.toFixed(1)}%
                              </div>
                              <div style={{ color: isDarkMode ? '#6b7280' : '#9ca3af' }}>
                                {product.daysRemaining}d
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Footer */}
      <div style={{
        marginTop: '3rem',
        paddingTop: '2rem',
        borderTop: `1px solid ${isDarkMode ? '#374151' : '#e5e7eb'}`,
        textAlign: 'center',
        color: isDarkMode ? '#6b7280' : '#9ca3af',
        fontSize: '0.85rem'
      }}>
        <p style={{ margin: '0 0 0.5rem 0' }}>
          This report was generated using Amberlake analysis
        </p>
        <p style={{ margin: 0 }}>
          For questions or concerns, please contact the Risk Management team
        </p>
      </div>
    </div>
  );
};

export default RiskAnalysisReport;
