import React from 'react';
import { Section, DateInput, Badge, Btn, thStyle, tdStyle } from '../formControls.jsx';
import { explodeSchedule, applyScheduleEdit, clearScheduleOverride } from '../canvas/schedulePreview.js';

/**
 * Schedule tab: every observation the product generates, with editable
 * observation/payment dates. Editing a loop-generated date stores a per-period
 * override (e.g. to move a fixing off a holiday) that survives recompile;
 * single-observation lines edit their date directly.
 */
const SCHEDULE_CAP = 150; // avoid rendering a date picker per day for daily loops

export default function ScheduleTab({ lines, onChange, finalObservationDate }) {
  const allRows = explodeSchedule(lines, finalObservationDate);
  const rows = allRows.slice(0, SCHEDULE_CAP);
  const truncated = allRows.length - rows.length;

  return (
    <Section
      title="Schedule"
      subtitle="Observation and payment dates generated by your loops and observation lines. Edit a date to shift a fixing (e.g. off a holiday) — loop edits are stored as per-date overrides."
    >
      {rows.length === 0 ? (
        <div style={{ color: 'var(--text-muted)', padding: '1rem' }}>
          No scheduled observations — this product has no loops or observation lines yet.
        </div>
      ) : (
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr>
                <th style={thStyle}>#</th>
                <th style={thStyle}>Observation date</th>
                <th style={thStyle}>Payment date</th>
                <th style={thStyle}>Levels</th>
                <th style={thStyle}>Rules</th>
                <th style={thStyle}>Source</th>
                <th style={thStyle}></th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r, i) => {
                const levelsText = Object.entries(r.levels || {}).map(([k, v]) => `${k} ${v}`).join(' · ') || '—';
                const isOverridden = r.obsOverridden || r.payOverridden;
                return (
                  <tr key={r.key} style={isOverridden ? { background: 'rgba(245,158,11,0.06)' } : undefined}>
                    <td style={{ ...tdStyle, color: 'var(--text-muted)' }}>{i + 1}</td>
                    <td style={{ ...tdStyle, minWidth: '150px' }}>
                      <DateInput value={r.observationDate} onChange={v => onChange(applyScheduleEdit(lines, r, 'observationDate', v))} />
                    </td>
                    <td style={{ ...tdStyle, minWidth: '150px' }}>
                      <DateInput value={r.paymentDate} onChange={v => onChange(applyScheduleEdit(lines, r, 'paymentDate', v))} />
                    </td>
                    <td style={{ ...tdStyle, fontSize: '0.78rem', color: 'var(--text-secondary)' }}>{levelsText}</td>
                    <td style={tdStyle}>{r.eventCount}</td>
                    <td style={tdStyle}>
                      {r.lineType === 'loop'
                        ? <Badge tone="purple">loop{isOverridden ? ' · edited' : ''}</Badge>
                        : <Badge tone="gray">observation</Badge>}
                    </td>
                    <td style={tdStyle}>
                      {r.lineType === 'loop' && isOverridden && (
                        <Btn small onClick={() => onChange(clearScheduleOverride(lines, r))} title="Revert to the generated date">reset</Btn>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {truncated > 0 && (
            <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem', marginTop: '0.6rem' }}>
              Showing the first {SCHEDULE_CAP} observations; {truncated} more are generated and will be evaluated. (High-frequency schedules aren't fully listed here.)
            </div>
          )}
        </div>
      )}
    </Section>
  );
}
