/**
 * Report Translations for PDF Generation
 * Supports English (en) and French (fr)
 */

export const translations = {
  en: {
    // Common labels
    generatedBy: 'Generated by Amberlake Partners',
    initialLevel: 'Initial Level',
    currentLevel: 'Current Level',
    redemptionLevel: 'Redemption Level',
    performance: 'Performance',
    payout: 'Payout',
    date: 'Date',
    asset: 'Asset',
    currency: 'Currency',
    isin: 'ISIN',

    // Section titles
    underlyingAssetsPerformance: 'Underlying Assets Performance',
    performanceOverview: 'Performance Overview',
    capitalProtectionAnalysis: 'Capital Protection Analysis',
    observationSchedule: 'Observation Schedule',
    performanceEvolution: 'Performance Evolution',
    latestNews: 'Latest News',

    // Barrier related
    barrierDistance: 'Barrier Distance',
    protectionBarrier: 'Protection Barrier',
    autocallBarrier: 'Autocall Barrier',
    couponBarrier: 'Coupon Barrier',
    upperBarrier: 'Upper Barrier',
    barrier: 'Barrier',

    // Status labels
    aboveBarrier: 'Above Barrier',
    nearBarrier: 'Near Barrier',
    belowBarrier: 'Below Barrier',
    safe: 'Safe',
    warning: 'Warning',
    breached: 'Breached',
    aboveBarrierSafe: 'Above Barrier (Safe)',
    nearBarrierWarning: 'Near Barrier (Warning)',
    belowBarrierBreached: 'Below Barrier (Breached)',

    // Protection analysis
    criticalDistance: 'Critical Distance',

    // Observation schedule
    observation: 'Observation',
    payment: 'Payment',
    type: 'Type',
    trigger: 'Trigger',
    autocall: 'Autocall',
    coupon: 'Coupon',
    memory: 'Memory',
    memoryLock: 'Memory Lock',
    totalCouponsEarned: 'Total Coupons Earned',
    inMemory: 'In Memory',
    totalObservations: 'Total Observations',
    remaining: 'Remaining',
    redeemed: 'Redeemed',
    called: 'Called',
    matured: 'Matured',
    memoryAutocall: 'Memory Autocall',
    memoryCoupon: 'Memory Coupon',
    tbd: 'TBD',
    yes: 'YES',
    no: 'NO',
    paid: 'PAID',
    overdue: 'OVERDUE',
    pending: 'PENDING',
    redeemed: 'REDEEMED',
    allFlagged: 'All Flagged',

    // Next observation prediction
    nextObservationPrediction: 'Next Observation Prediction',
    days: 'days',
    predictedOutcome: 'Predicted Outcome',
    currentBasket: 'Current Basket',
    autocallAt: 'Autocall at',
    finalRedemption: 'Final Redemption',
    noCouponWouldBePaid: 'No coupon would be paid',
    addedToMemory: 'Added to Memory',
    total: 'Total',

    // Indicative maturity value
    indicativeValueIfMaturedToday: 'Indicative Value If Matured Today',
    hypothetical: 'Hypothetical',
    indicativeCalculationDisclaimer: 'This is an indicative calculation showing what you would receive if the product matured today based on current market prices. Actual redemption value at maturity may differ.',
    currentTheoreticalTotalReturn: 'Current theoretical Total return',
    asOf: 'As of',
    capitalReturn: 'Capital Return',
    couponsEarned: 'Coupons Earned',
    totalCouponsPaidToDate: 'Total coupons paid to date',
    memoryCoupons: 'Memory Coupons',
    accumulatedInMemory: 'Accumulated in memory',
    forfeitedBelowBarrier: 'Forfeited (below barrier)',

    // Phoenix specific
    phoenixEvaluationResults: 'Phoenix Evaluation Results',
    observationFrequency: 'Observation Frequency',

    // Orion specific
    orionMemoryEvaluationResults: 'Orion Memory Evaluation Results',
    considered: 'Considered',

    // Himalaya specific
    himalayaEvaluationResults: 'Himalaya Evaluation Results',
    finalAveragePerformance: 'Final Average Performance',
    currentAveragePerformance: 'Current Average Performance',
    finalFlooredPerformance: 'Final Floored Performance',
    indicativeFlooredPerformance: 'Indicative Floored Performance',
    finalPayout: 'Final Payout',
    indicativePayoutIfMaturedToday: 'Indicative Payout (If Matured Today)',
    floorApplied: 'Floor applied: Performance below {floor}% floor',
    indicativeCalculationBasedOnCurrentPrices: 'This is an indicative calculation based on current market prices.',
    performanceSummary: 'Performance Summary',
    obsNumber: 'Obs #',
    bestPerformer: 'Best Performer',
    observationLevel: 'Observation Level',
    finalLevel: 'Final Level',
    remainingUnderlying: 'Remaining',

    // Participation Note specific
    participationNoteEvaluationResults: 'Participation Note Evaluation Results',
    productCalledByIssuer: 'PRODUCT CALLED BY ISSUER',
    productWasEarlyRedeemedOn: 'This product was early redeemed on',

    // Risk Analysis
    riskAnalysisReport: 'Risk Analysis Report',
    portfolioRiskSummary: 'Portfolio Risk Summary',
    totalExposure: 'Total Exposure',
    averageDistanceToBarrier: 'Average Distance to Barrier',
    productsAtRisk: 'Products at Risk',
    productsNearBarrier: 'Products Near Barrier',
    underlyingExposure: 'Underlying Exposure',
    productDetails: 'Product Details',

    // PMS Report
    portfolioManagementReport: 'Portfolio Management Report',
    positions: 'Positions',
    transactions: 'Transactions',
    holdings: 'Holdings',
    marketValue: 'Market Value',
    costBasis: 'Cost Basis',
    unrealizedPL: 'Unrealized P&L',
    weight: 'Weight',

    // Badges/Status
    worstPerforming: 'Worst Performing',
    flaggedForMemoryAutocall: 'Flagged for Memory Autocall on',
    protectionAt: 'Protection at',

    // Report footer
    pageOf: 'Page {current} of {total}',
    confidential: 'Confidential',

    // Misc
    noDataAvailable: 'No data available',
    loading: 'Loading...',
    error: 'Error',
    selectReportLanguage: 'Select Report Language',
    cancel: 'Cancel',
    english: 'English',
    french: 'Français'
  },

  fr: {
    // Common labels
    generatedBy: 'Généré par Amberlake Partners',
    initialLevel: 'Niveau Initial',
    currentLevel: 'Niveau Actuel',
    redemptionLevel: 'Niveau de Remboursement',
    performance: 'Performance',
    payout: 'Remboursement',
    date: 'Date',
    asset: 'Actif',
    currency: 'Devise',
    isin: 'ISIN',

    // Section titles
    underlyingAssetsPerformance: 'Performance des Sous-jacents',
    performanceOverview: 'Aperçu de la Performance',
    capitalProtectionAnalysis: 'Analyse de la Protection du Capital',
    observationSchedule: 'Calendrier des Observations',
    performanceEvolution: 'Évolution de la Performance',
    latestNews: 'Dernières Actualités',

    // Barrier related
    barrierDistance: 'Distance à la Barrière',
    protectionBarrier: 'Barrière de Protection',
    autocallBarrier: 'Barrière Autocall',
    couponBarrier: 'Barrière Coupon',
    upperBarrier: 'Barrière Supérieure',
    barrier: 'Barrière',

    // Status labels
    aboveBarrier: 'Au-dessus de la Barrière',
    nearBarrier: 'Proche de la Barrière',
    belowBarrier: 'Sous la Barrière',
    safe: 'Sûr',
    warning: 'Attention',
    breached: 'Franchie',
    aboveBarrierSafe: 'Au-dessus (Sûr)',
    nearBarrierWarning: 'Proche (Attention)',
    belowBarrierBreached: 'Sous la Barrière (Franchie)',

    // Protection analysis
    criticalDistance: 'Distance Critique',

    // Observation schedule
    observation: 'Observation',
    payment: 'Paiement',
    type: 'Type',
    trigger: 'Déclencheur',
    autocall: 'Autocall',
    coupon: 'Coupon',
    memory: 'Mémoire',
    memoryLock: 'Verrouillage Mémoire',
    totalCouponsEarned: 'Total des Coupons Gagnés',
    inMemory: 'En Mémoire',
    totalObservations: 'Total des Observations',
    remaining: 'Restant',
    redeemed: 'Remboursé',
    called: 'Rappelé',
    matured: 'À Maturité',
    memoryAutocall: 'Autocall Mémoire',
    memoryCoupon: 'Coupon Mémoire',
    tbd: 'À déterminer',
    yes: 'OUI',
    no: 'NON',
    paid: 'PAYÉ',
    overdue: 'EN RETARD',
    pending: 'EN ATTENTE',
    redeemed: 'REMBOURSÉ',
    allFlagged: 'Tous Marqués',

    // Next observation prediction
    nextObservationPrediction: 'Prévision Prochaine Observation',
    days: 'jours',
    predictedOutcome: 'Résultat Prévu',
    currentBasket: 'Panier Actuel',
    autocallAt: 'Autocall à',
    finalRedemption: 'Remboursement Final',
    noCouponWouldBePaid: 'Aucun coupon ne serait payé',
    addedToMemory: 'Ajouté en Mémoire',
    total: 'Total',

    // Indicative maturity value
    indicativeValueIfMaturedToday: 'Valeur Indicative si Maturité Aujourd\'hui',
    hypothetical: 'Hypothétique',
    indicativeCalculationDisclaimer: 'Ceci est un calcul indicatif montrant ce que vous recevriez si le produit arrivait à maturité aujourd\'hui aux prix actuels du marché. La valeur réelle de remboursement à maturité peut différer.',
    currentTheoreticalTotalReturn: 'Rendement Total Théorique Actuel',
    asOf: 'Au',
    capitalReturn: 'Retour du Capital',
    couponsEarned: 'Coupons Gagnés',
    totalCouponsPaidToDate: 'Total des coupons payés à ce jour',
    memoryCoupons: 'Coupons Mémoire',
    accumulatedInMemory: 'Accumulé en mémoire',
    forfeitedBelowBarrier: 'Perdu (sous la barrière)',

    // Phoenix specific
    phoenixEvaluationResults: 'Résultats d\'Évaluation Phoenix',
    observationFrequency: 'Fréquence d\'Observation',

    // Orion specific
    orionMemoryEvaluationResults: 'Résultats d\'Évaluation Orion Memory',
    considered: 'Considéré',

    // Himalaya specific
    himalayaEvaluationResults: 'Résultats d\'Évaluation Himalaya',
    finalAveragePerformance: 'Performance Moyenne Finale',
    currentAveragePerformance: 'Performance Moyenne Actuelle',
    finalFlooredPerformance: 'Performance Plancher Finale',
    indicativeFlooredPerformance: 'Performance Plancher Indicative',
    finalPayout: 'Remboursement Final',
    indicativePayoutIfMaturedToday: 'Remboursement Indicatif (Si Maturité Aujourd\'hui)',
    floorApplied: 'Plancher appliqué: Performance sous le plancher de {floor}%',
    indicativeCalculationBasedOnCurrentPrices: 'Ceci est un calcul indicatif basé sur les prix actuels du marché.',
    performanceSummary: 'Résumé de la Performance',
    obsNumber: 'Obs N°',
    bestPerformer: 'Meilleur Performeur',
    observationLevel: 'Niveau d\'Observation',
    finalLevel: 'Niveau Final',
    remainingUnderlying: 'Restant',

    // Participation Note specific
    participationNoteEvaluationResults: 'Résultats d\'Évaluation Note de Participation',
    productCalledByIssuer: 'PRODUIT RAPPELÉ PAR L\'ÉMETTEUR',
    productWasEarlyRedeemedOn: 'Ce produit a été remboursé par anticipation le',

    // Risk Analysis
    riskAnalysisReport: 'Rapport d\'Analyse des Risques',
    portfolioRiskSummary: 'Résumé des Risques du Portefeuille',
    totalExposure: 'Exposition Totale',
    averageDistanceToBarrier: 'Distance Moyenne à la Barrière',
    productsAtRisk: 'Produits à Risque',
    productsNearBarrier: 'Produits Proches de la Barrière',
    underlyingExposure: 'Exposition aux Sous-jacents',
    productDetails: 'Détails du Produit',

    // PMS Report
    portfolioManagementReport: 'Rapport de Gestion de Portefeuille',
    positions: 'Positions',
    transactions: 'Transactions',
    holdings: 'Avoirs',
    marketValue: 'Valeur de Marché',
    costBasis: 'Coût de Base',
    unrealizedPL: 'P&L Non Réalisé',
    weight: 'Poids',

    // Badges/Status
    worstPerforming: 'Moins Performant',
    flaggedForMemoryAutocall: 'Marqué pour Autocall Mémoire le',
    protectionAt: 'Protection à',

    // Report footer
    pageOf: 'Page {current} sur {total}',
    confidential: 'Confidentiel',

    // Misc
    noDataAvailable: 'Aucune donnée disponible',
    loading: 'Chargement...',
    error: 'Erreur',
    selectReportLanguage: 'Sélectionner la Langue du Rapport',
    cancel: 'Annuler',
    english: 'English',
    french: 'Français'
  }
};

/**
 * Get translation object for a specific language
 * @param {string} lang - Language code ('en' or 'fr')
 * @returns {object} Translation object
 */
export const getTranslation = (lang = 'en') => {
  return translations[lang] || translations.en;
};

/**
 * Get a specific translation key with optional variable substitution
 * @param {string} lang - Language code
 * @param {string} key - Translation key
 * @param {object} vars - Variables to substitute (e.g., {floor: 70})
 * @returns {string} Translated string
 */
export const t = (lang, key, vars = {}) => {
  const translation = getTranslation(lang);
  let text = translation[key] || translations.en[key] || key;

  // Substitute variables like {floor} with actual values
  Object.keys(vars).forEach(varKey => {
    text = text.replace(new RegExp(`\\{${varKey}\\}`, 'g'), vars[varKey]);
  });

  return text;
};

/**
 * Get locale string for date/number formatting
 * @param {string} lang - Language code
 * @returns {string} Locale string
 */
export const getLocale = (lang = 'en') => {
  return lang === 'fr' ? 'fr-FR' : 'en-GB';
};

export default translations;
