import React, { useEffect, useState } from 'react';
import { useTracker } from 'meteor/react-meteor-data';
import { ProductsCollection } from '../api/products';
import { TemplateReportsCollection } from '../api/templateReports';

/**
 * Printable Product Report Component
 *
 * Optimized layout for printing with proper table handling
 * Opens in a new window, designed for print-to-PDF
 */
const PrintableProductReport = () => {
  const [isReady, setIsReady] = useState(false);

  // Get productId from URL path
  const productId = typeof window !== 'undefined'
    ? window.location.pathname.split('/').pop()
    : null;

  // Get session ID from localStorage
  const sessionId = typeof window !== 'undefined' ? localStorage.getItem('sessionId') : null;

  // Subscribe to product and report data
  const { product, latestReport, isLoading } = useTracker(() => {
    const productSub = Meteor.subscribe('products.single', productId, sessionId);
    const reportsSub = Meteor.subscribe('templateReports.forProduct', productId, sessionId);

    const prod = ProductsCollection.findOne(productId);
    const report = TemplateReportsCollection.findOne(
      { productId },
      { sort: { generatedAt: -1 } }
    );

    return {
      product: prod,
      latestReport: report,
      isLoading: !productSub.ready() || !reportsSub.ready()
    };
  }, [productId, sessionId]);

  useEffect(() => {
    if (!isLoading && product && latestReport) {
      // Wait a bit for charts to render, then auto-trigger print
      setTimeout(() => {
        setIsReady(true);
        window.print();
      }, 1500);
    }
  }, [isLoading, product, latestReport]);

  if (isLoading) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center' }}>
        <p>Loading report data...</p>
      </div>
    );
  }

  if (!product || !latestReport) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center' }}>
        <p>Report not found</p>
      </div>
    );
  }

  const { templateResults } = latestReport;
  const displayProduct = product.displayProduct || product;

  return (
    <div className="printable-report">
      <style>{printStyles}</style>

      {/* Header */}
      <div className="print-header">
        <h1>{displayProduct.productName || displayProduct.title || 'Product Report'}</h1>
        <div className="report-meta">
          <span>Generated: {new Date().toLocaleDateString()}</span>
          {displayProduct.isin && <span>ISIN: {displayProduct.isin}</span>}
        </div>
      </div>

      {/* Product Overview */}
      {templateResults && renderProductOverview(templateResults, displayProduct)}

      {/* Template Results */}
      {templateResults && Object.keys(templateResults).length > 0 &&
        renderTemplateResults(templateResults)}

      {/* Footer */}
      <div className="print-footer">
        <p>Generated by Amberlake Partners • {new Date().toLocaleString()}</p>
      </div>
    </div>
  );
};

// Render product overview section
function renderProductOverview(templateResults, product) {
  const overview = templateResults.productOverview || templateResults.summary;

  if (!overview) return null;

  return (
    <div className="section overview-section">
      <h2>Product Overview</h2>
      <div className="overview-grid">
        {product.productType && (
          <div className="overview-item">
            <strong>Product Type:</strong>
            <span>{product.productType}</span>
          </div>
        )}
        {product.initialDate && (
          <div className="overview-item">
            <strong>Initial Date:</strong>
            <span>{new Date(product.initialDate).toLocaleDateString()}</span>
          </div>
        )}
        {product.maturityDate && (
          <div className="overview-item">
            <strong>Maturity Date:</strong>
            <span>{new Date(product.maturityDate).toLocaleDateString()}</span>
          </div>
        )}
        {product.issuer && (
          <div className="overview-item">
            <strong>Issuer:</strong>
            <span>{product.issuer}</span>
          </div>
        )}
      </div>
    </div>
  );
}

// Render template results
function renderTemplateResults(templateResults) {
  return Object.entries(templateResults).map(([widgetType, widgetData], index) => {
    // Skip overview as it's rendered separately
    if (widgetType === 'productOverview' || widgetType === 'summary') return null;

    return (
      <div key={widgetType + index} className="section">
        {renderWidget(widgetType, widgetData)}
      </div>
    );
  });
}

// Render individual widgets
function renderWidget(widgetType, widgetData) {
  switch (widgetType) {
    case 'underlyingPerformance':
      return renderUnderlyingPerformance(widgetData);
    case 'barrierMonitor':
      return renderBarrierMonitor(widgetData);
    case 'couponSchedule':
      return renderCouponSchedule(widgetData);
    case 'payoffScenarios':
      return renderPayoffScenarios(widgetData);
    case 'riskMetrics':
      return renderRiskMetrics(widgetData);
    default:
      return renderGenericWidget(widgetType, widgetData);
  }
}

// Render underlying performance
function renderUnderlyingPerformance(data) {
  if (!data.underlyings) return null;

  return (
    <div className="widget">
      <h2>Underlying Performance</h2>
      <table className="data-table">
        <thead>
          <tr>
            <th>Ticker</th>
            <th>Name</th>
            <th>Initial Price</th>
            <th>Current Price</th>
            <th>Performance</th>
          </tr>
        </thead>
        <tbody>
          {data.underlyings.map((underlying, idx) => (
            <tr key={idx}>
              <td>{underlying.ticker}</td>
              <td>{underlying.name}</td>
              <td>{underlying.initialPriceFormatted || underlying.initialPrice}</td>
              <td>{underlying.currentPriceFormatted || underlying.currentPrice}</td>
              <td className={underlying.isPositive ? 'positive' : 'negative'}>
                {underlying.performanceFormatted}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// Render barrier monitor
function renderBarrierMonitor(data) {
  if (!data.barriers) return null;

  return (
    <div className="widget">
      <h2>Barrier Monitor</h2>
      <table className="data-table">
        <thead>
          <tr>
            <th>Barrier Type</th>
            <th>Level</th>
            <th>Current Distance</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {data.barriers.map((barrier, idx) => (
            <tr key={idx}>
              <td>{barrier.name}</td>
              <td>{barrier.levelFormatted || barrier.level}</td>
              <td>{barrier.distanceFormatted || barrier.distance}</td>
              <td className={barrier.isSafe ? 'safe' : 'at-risk'}>
                {barrier.status}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// Render coupon schedule
function renderCouponSchedule(data) {
  if (!data.schedule) return null;

  return (
    <div className="widget">
      <h2>Coupon Schedule</h2>
      <table className="data-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Coupon Rate</th>
            <th>Amount</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {data.schedule.map((item, idx) => (
            <tr key={idx}>
              <td>{item.dateFormatted || new Date(item.date).toLocaleDateString()}</td>
              <td>{item.rateFormatted || item.rate}</td>
              <td>{item.amountFormatted || item.amount}</td>
              <td>{item.status}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// Render payoff scenarios
function renderPayoffScenarios(data) {
  if (!data.scenarios) return null;

  return (
    <div className="widget">
      <h2>Payoff Scenarios</h2>
      <table className="data-table">
        <thead>
          <tr>
            <th>Scenario</th>
            <th>Underlying Level</th>
            <th>Return</th>
            <th>Probability</th>
          </tr>
        </thead>
        <tbody>
          {data.scenarios.map((scenario, idx) => (
            <tr key={idx}>
              <td>{scenario.name}</td>
              <td>{scenario.levelFormatted || scenario.level}</td>
              <td className={scenario.isPositive ? 'positive' : 'negative'}>
                {scenario.returnFormatted}
              </td>
              <td>{scenario.probabilityFormatted || scenario.probability}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// Render risk metrics
function renderRiskMetrics(data) {
  if (!data.metrics) return null;

  return (
    <div className="widget">
      <h2>Risk Metrics</h2>
      <div className="metrics-grid">
        {Object.entries(data.metrics).map(([key, value]) => (
          <div key={key} className="metric-item">
            <div className="metric-label">{key}</div>
            <div className="metric-value">{value}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

// Render generic widget (fallback)
function renderGenericWidget(widgetType, widgetData) {
  return (
    <div className="widget">
      <h2>{widgetType.replace(/([A-Z])/g, ' $1').trim()}</h2>
      <pre>{JSON.stringify(widgetData, null, 2)}</pre>
    </div>
  );
}

// Print-optimized styles
const printStyles = `
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  @page {
    size: A4;
    margin: 15mm 10mm;
  }

  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica', 'Arial', sans-serif;
    font-size: 9pt;
    line-height: 1.4;
    color: #1f2937;
    background: white;
  }

  .printable-report {
    max-width: 100%;
    padding: 0;
  }

  .print-header {
    margin-bottom: 1.5rem;
    padding-bottom: 0.75rem;
    border-bottom: 2px solid #e5e7eb;
  }

  .print-header h1 {
    font-size: 18pt;
    font-weight: 600;
    margin-bottom: 0.5rem;
    color: #111827;
  }

  .report-meta {
    display: flex;
    gap: 1.5rem;
    font-size: 8pt;
    color: #6b7280;
  }

  .section {
    page-break-inside: avoid;
    margin-bottom: 1.5rem;
  }

  h2 {
    font-size: 13pt;
    font-weight: 600;
    margin-bottom: 0.75rem;
    color: #374151;
    page-break-after: avoid;
  }

  .widget {
    page-break-inside: avoid;
  }

  /* Tables */
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 1rem;
    page-break-inside: auto;
  }

  thead {
    display: table-header-group;
  }

  tr {
    page-break-inside: avoid;
    page-break-after: auto;
  }

  th, td {
    padding: 0.35rem 0.5rem;
    text-align: left;
    border-bottom: 1px solid #e5e7eb;
    font-size: 8pt;
  }

  th {
    background-color: #f3f4f6;
    font-weight: 600;
    color: #374151;
    border-bottom: 2px solid #d1d5db;
  }

  tbody tr:nth-child(even) {
    background-color: #f9fafb;
  }

  /* Color coding */
  .positive {
    color: #059669;
    font-weight: 500;
  }

  .negative {
    color: #dc2626;
    font-weight: 500;
  }

  .safe {
    color: #059669;
  }

  .at-risk {
    color: #dc2626;
  }

  /* Overview grid */
  .overview-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 0.75rem;
    margin-bottom: 1rem;
  }

  .overview-item {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    padding: 0.5rem;
    background: #f9fafb;
    border-radius: 4px;
  }

  .overview-item strong {
    font-size: 7pt;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .overview-item span {
    font-size: 9pt;
    color: #111827;
  }

  /* Metrics grid */
  .metrics-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 0.75rem;
  }

  .metric-item {
    padding: 0.5rem;
    background: #f9fafb;
    border-radius: 4px;
    page-break-inside: avoid;
  }

  .metric-label {
    font-size: 7pt;
    color: #6b7280;
    text-transform: uppercase;
    margin-bottom: 0.25rem;
  }

  .metric-value {
    font-size: 11pt;
    font-weight: 600;
    color: #111827;
  }

  /* Footer */
  .print-footer {
    margin-top: 2rem;
    padding-top: 0.75rem;
    border-top: 1px solid #e5e7eb;
    font-size: 7pt;
    color: #6b7280;
    text-align: center;
  }

  /* Print media query */
  @media print {
    body {
      print-color-adjust: exact;
      -webkit-print-color-adjust: exact;
    }

    .section {
      page-break-inside: avoid;
    }

    table {
      page-break-inside: auto;
    }

    tr {
      page-break-inside: avoid;
      page-break-after: auto;
    }

    thead {
      display: table-header-group;
    }
  }
`;

export default PrintableProductReport;
