/**
 * 200 Curated Investment & Finance Quotes
 * Used for daily quote rotation on the RM Dashboard
 */

export const INVESTMENT_QUOTES = [
  // Warren Buffett (20)
  { quote: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett" },
  { quote: "Be fearful when others are greedy and greedy when others are fearful.", author: "Warren Buffett" },
  { quote: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
  { quote: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { quote: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", author: "Warren Buffett" },
  { quote: "The most important investment you can make is in yourself.", author: "Warren Buffett" },
  { quote: "Someone's sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett" },
  { quote: "Never invest in a business you cannot understand.", author: "Warren Buffett" },
  { quote: "Our favorite holding period is forever.", author: "Warren Buffett" },
  { quote: "The best thing that happens to us is when a great company gets into temporary trouble.", author: "Warren Buffett" },
  { quote: "Time is the friend of the wonderful company, the enemy of the mediocre.", author: "Warren Buffett" },
  { quote: "Wide diversification is only required when investors do not understand what they are doing.", author: "Warren Buffett" },
  { quote: "If you aren't willing to own a stock for ten years, don't even think about owning it for ten minutes.", author: "Warren Buffett" },
  { quote: "Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.", author: "Warren Buffett" },
  { quote: "The difference between successful people and really successful people is that really successful people say no to almost everything.", author: "Warren Buffett" },
  { quote: "Only buy something that you'd be perfectly happy to hold if the market shut down for 10 years.", author: "Warren Buffett" },
  { quote: "Chains of habit are too light to be felt until they are too heavy to be broken.", author: "Warren Buffett" },
  { quote: "You only have to do a very few things right in your life so long as you don't do too many things wrong.", author: "Warren Buffett" },
  { quote: "The investor of today does not profit from yesterday's growth.", author: "Warren Buffett" },
  { quote: "What we learn from history is that people don't learn from history.", author: "Warren Buffett" },

  // Charlie Munger (15)
  { quote: "The big money is not in the buying and selling, but in the waiting.", author: "Charlie Munger" },
  { quote: "Spend each day trying to be a little wiser than you were when you woke up.", author: "Charlie Munger" },
  { quote: "Knowing what you don't know is more useful than being brilliant.", author: "Charlie Munger" },
  { quote: "The best thing a human being can do is to help another human being know more.", author: "Charlie Munger" },
  { quote: "In my whole life, I have known no wise people who didn't read all the time.", author: "Charlie Munger" },
  { quote: "It takes character to sit with all that cash and do nothing. I didn't get to where I am by going after mediocre opportunities.", author: "Charlie Munger" },
  { quote: "Develop into a lifelong self-learner through voracious reading.", author: "Charlie Munger" },
  { quote: "Take a simple idea and take it seriously.", author: "Charlie Munger" },
  { quote: "A lot of people with high IQs are terrible investors because they've got terrible temperaments.", author: "Charlie Munger" },
  { quote: "Those who keep learning will keep rising in life.", author: "Charlie Munger" },
  { quote: "The first rule is that you can't really know anything if you just remember isolated facts.", author: "Charlie Munger" },
  { quote: "I believe in the discipline of mastering the best that other people have ever figured out.", author: "Charlie Munger" },
  { quote: "Mimicking the herd invites regression to the mean.", author: "Charlie Munger" },
  { quote: "Acknowledging what you don't know is the dawning of wisdom.", author: "Charlie Munger" },
  { quote: "The iron rule of nature is: you get what you reward for.", author: "Charlie Munger" },

  // Benjamin Graham (10)
  { quote: "The intelligent investor is a realist who sells to optimists and buys from pessimists.", author: "Benjamin Graham" },
  { quote: "In the short run, the market is a voting machine but in the long run, it is a weighing machine.", author: "Benjamin Graham" },
  { quote: "The individual investor should act consistently as an investor and not as a speculator.", author: "Benjamin Graham" },
  { quote: "To achieve satisfactory investment results is easier than most people realize.", author: "Benjamin Graham" },
  { quote: "The margin of safety is always dependent on the price paid.", author: "Benjamin Graham" },
  { quote: "Those who do not remember the past are condemned to repeat it.", author: "Benjamin Graham" },
  { quote: "An investment operation is one which, upon thorough analysis, promises safety of principal and an adequate return.", author: "Benjamin Graham" },
  { quote: "The essence of investment management is the management of risks, not the management of returns.", author: "Benjamin Graham" },
  { quote: "Buy not on optimism, but on arithmetic.", author: "Benjamin Graham" },
  { quote: "The investor's chief problem—and even his worst enemy—is likely to be himself.", author: "Benjamin Graham" },

  // Peter Lynch (15)
  { quote: "Know what you own, and know why you own it.", author: "Peter Lynch" },
  { quote: "Go for a business that any idiot can run – because sooner or later, any idiot probably is going to run it.", author: "Peter Lynch" },
  { quote: "The person that turns over the most rocks wins the game.", author: "Peter Lynch" },
  { quote: "In this business, if you're good, you're right six times out of ten.", author: "Peter Lynch" },
  { quote: "Far more money has been lost by investors preparing for corrections than has been lost in corrections themselves.", author: "Peter Lynch" },
  { quote: "Never invest in any idea you can't illustrate with a crayon.", author: "Peter Lynch" },
  { quote: "Behind every stock is a company. Find out what it's doing.", author: "Peter Lynch" },
  { quote: "Time is on your side when you own shares of superior companies.", author: "Peter Lynch" },
  { quote: "The key to making money in stocks is not to get scared out of them.", author: "Peter Lynch" },
  { quote: "Investing without research is like playing stud poker and never looking at the cards.", author: "Peter Lynch" },
  { quote: "Everyone has the brainpower to make money in stocks. Not everyone has the stomach.", author: "Peter Lynch" },
  { quote: "You can't see the future through a rearview mirror.", author: "Peter Lynch" },
  { quote: "If you spend more than 13 minutes analyzing economic and market forecasts, you've wasted 10 minutes.", author: "Peter Lynch" },
  { quote: "All you need for a lifetime of successful investing is a few big winners.", author: "Peter Lynch" },
  { quote: "Selling your winners and holding your losers is like cutting the flowers and watering the weeds.", author: "Peter Lynch" },

  // Ray Dalio (12)
  { quote: "He who lives by the crystal ball will eat shattered glass.", author: "Ray Dalio" },
  { quote: "Pain plus reflection equals progress.", author: "Ray Dalio" },
  { quote: "If you're not failing, you're not pushing your limits.", author: "Ray Dalio" },
  { quote: "The biggest mistake investors make is to believe that what happened in the recent past is likely to persist.", author: "Ray Dalio" },
  { quote: "Don't let artificial constraints limit your possibilities.", author: "Ray Dalio" },
  { quote: "Truth—more precisely, an accurate understanding of reality—is the essential foundation for any good outcome.", author: "Ray Dalio" },
  { quote: "Embrace reality and deal with it.", author: "Ray Dalio" },
  { quote: "Diversifying well is the most important thing you need to do in order to invest well.", author: "Ray Dalio" },
  { quote: "The greatest gift you can give someone is the power to be successful.", author: "Ray Dalio" },
  { quote: "Look at what happened in the past and figure out what's likely to happen in the future.", author: "Ray Dalio" },
  { quote: "Don't worry about looking good—worry about achieving your goals.", author: "Ray Dalio" },
  { quote: "Radical open-mindedness is the key to learning and improvement.", author: "Ray Dalio" },

  // Howard Marks (12)
  { quote: "The biggest investing errors come not from factors that are informational or analytical, but from those that are psychological.", author: "Howard Marks" },
  { quote: "You can't predict. You can prepare.", author: "Howard Marks" },
  { quote: "Experience is what you got when you didn't get what you wanted.", author: "Howard Marks" },
  { quote: "The most important thing is being aware of where we are in the cycle.", author: "Howard Marks" },
  { quote: "There's little that's as dangerous for investor health as insistence on extrapolating today's events into the future.", author: "Howard Marks" },
  { quote: "Investment success doesn't come from buying good things, but from buying things well.", author: "Howard Marks" },
  { quote: "The market is not a weighing machine. It's a voting machine.", author: "Howard Marks" },
  { quote: "Good investing isn't about making big gains; it's about consistently avoiding losses.", author: "Howard Marks" },
  { quote: "Being too far ahead of your time is indistinguishable from being wrong.", author: "Howard Marks" },
  { quote: "Risk means more things can happen than will happen.", author: "Howard Marks" },
  { quote: "The most dangerous thing is to buy something at the peak of its popularity.", author: "Howard Marks" },
  { quote: "Second-level thinking is deep, complex, and convoluted.", author: "Howard Marks" },

  // John Bogle (12)
  { quote: "Don't look for the needle in the haystack. Just buy the haystack.", author: "John Bogle" },
  { quote: "Time is your friend; impulse is your enemy.", author: "John Bogle" },
  { quote: "The stock market is a giant distraction to the business of investing.", author: "John Bogle" },
  { quote: "If you have trouble imagining a 20% loss in the stock market, you shouldn't be in stocks.", author: "John Bogle" },
  { quote: "Stay the course. The best strategy for building wealth is to invest regularly and never stop.", author: "John Bogle" },
  { quote: "In investing, you get what you don't pay for.", author: "John Bogle" },
  { quote: "The two greatest enemies of the equity fund investor are expenses and emotions.", author: "John Bogle" },
  { quote: "Invest you must. The biggest risk is the long-term risk of not putting your money to work.", author: "John Bogle" },
  { quote: "Rely on the ordinary virtues that intelligent, balanced human beings have relied on for centuries.", author: "John Bogle" },
  { quote: "The idea that a bell rings to signal when investors should get into or out of the market is simply not credible.", author: "John Bogle" },
  { quote: "Successful investing is about owning businesses and reaping the returns.", author: "John Bogle" },
  { quote: "The miracle of compounding returns is overwhelmed by the tyranny of compounding costs.", author: "John Bogle" },

  // George Soros (8)
  { quote: "It's not whether you're right or wrong that's important, but how much money you make when you're right and how much you lose when you're wrong.", author: "George Soros" },
  { quote: "The financial markets generally are unpredictable.", author: "George Soros" },
  { quote: "I'm only rich because I know when I'm wrong.", author: "George Soros" },
  { quote: "Markets are constantly in a state of uncertainty and flux.", author: "George Soros" },
  { quote: "Once we realize that imperfect understanding is the human condition, there is no shame in being wrong, only in failing to correct our mistakes.", author: "George Soros" },
  { quote: "If investing is entertaining, if you're having fun, you're probably not making any money.", author: "George Soros" },
  { quote: "The worse a situation becomes, the less it takes to turn it around.", author: "George Soros" },
  { quote: "My approach works not by making valid predictions but by allowing me to correct false ones.", author: "George Soros" },

  // Seth Klarman (8)
  { quote: "The stock market is the story of cycles and of the human behavior that is responsible for overreactions in both directions.", author: "Seth Klarman" },
  { quote: "Value investing is at its core the marriage of a contrarian streak and a calculator.", author: "Seth Klarman" },
  { quote: "Investors should always keep in mind that the most important metric is not the returns achieved but the returns weighed against the risks incurred.", author: "Seth Klarman" },
  { quote: "Beware of leverage in all its forms.", author: "Seth Klarman" },
  { quote: "The best opportunities are usually found among things most others won't do.", author: "Seth Klarman" },
  { quote: "The trick of successful investors is to sell when they want to, not when they have to.", author: "Seth Klarman" },
  { quote: "Rather than targeting a desired rate of return, investors should target risk.", author: "Seth Klarman" },
  { quote: "An investor who earns 16% return over a decade will end up with more money than an investor who earns 20% for nine years and then loses 15% in the tenth year.", author: "Seth Klarman" },

  // Philip Fisher (8)
  { quote: "The stock market is filled with individuals who know the price of everything, but the value of nothing.", author: "Philip Fisher" },
  { quote: "I don't want a lot of good investments; I want a few outstanding ones.", author: "Philip Fisher" },
  { quote: "Conservative investors sleep well.", author: "Philip Fisher" },
  { quote: "The best time to sell is almost never.", author: "Philip Fisher" },
  { quote: "Excellent management is the most important factor in a common stock investment.", author: "Philip Fisher" },
  { quote: "Is the company doing things now that will maintain or improve profit margins in the future?", author: "Philip Fisher" },
  { quote: "Do what you enjoy most. Find something you are passionate about.", author: "Philip Fisher" },
  { quote: "The greatest investment reward comes to those who by good luck or good sense find the occasional company that can grow in sales and profits far more than industry as a whole.", author: "Philip Fisher" },

  // John Templeton (8)
  { quote: "Bull markets are born on pessimism, grown on skepticism, mature on optimism, and die on euphoria.", author: "John Templeton" },
  { quote: "The four most dangerous words in investing are: 'This time it's different.'", author: "John Templeton" },
  { quote: "If you want to have a better performance than the crowd, you must do things differently from the crowd.", author: "John Templeton" },
  { quote: "To buy when others are despondently selling and to sell when others are avidly buying requires the greatest fortitude.", author: "John Templeton" },
  { quote: "Invest at the point of maximum pessimism.", author: "John Templeton" },
  { quote: "Focus on value because most investors focus on outlooks and trends.", author: "John Templeton" },
  { quote: "The time of maximum pessimism is the best time to buy.", author: "John Templeton" },
  { quote: "An investor who has all the answers doesn't even understand the questions.", author: "John Templeton" },

  // Jesse Livermore (6)
  { quote: "The market does not beat them. They beat themselves, because though they have brains they cannot sit tight.", author: "Jesse Livermore" },
  { quote: "There is nothing new on Wall Street. Whatever happens in the stock market today has happened before and will happen again.", author: "Jesse Livermore" },
  { quote: "The game of speculation is the most uniformly fascinating game in the world.", author: "Jesse Livermore" },
  { quote: "It never was my thinking that made the big money for me. It was always my sitting.", author: "Jesse Livermore" },
  { quote: "Men who can both be right and sit tight are uncommon.", author: "Jesse Livermore" },
  { quote: "A loss never troubles me after I take it. I forget it overnight.", author: "Jesse Livermore" },

  // Carl Icahn (5)
  { quote: "In life and business, there are two cardinal sins: the first is to act precipitously without thought, and the second is to not act at all.", author: "Carl Icahn" },
  { quote: "Don't confuse luck with skill when judging others, and especially when judging yourself.", author: "Carl Icahn" },
  { quote: "When most investors, including the pros, all agree on something, they're usually wrong.", author: "Carl Icahn" },
  { quote: "You learn in this business that if you want a friend, get a dog.", author: "Carl Icahn" },
  { quote: "A great company in a good industry will almost always outperform a good company in a great industry.", author: "Carl Icahn" },

  // Bernard Baruch (5)
  { quote: "Don't try to buy at the bottom and sell at the top. It can't be done except by liars.", author: "Bernard Baruch" },
  { quote: "The main purpose of the stock market is to make fools of as many men as possible.", author: "Bernard Baruch" },
  { quote: "Nobody ever lost money taking a profit.", author: "Bernard Baruch" },
  { quote: "I made my money by selling too soon.", author: "Bernard Baruch" },
  { quote: "Whatever failures I have known, whatever errors I have committed, have been the consequence of action without thought.", author: "Bernard Baruch" },

  // Nassim Taleb (8)
  { quote: "The three most harmful addictions are heroin, carbohydrates, and a monthly salary.", author: "Nassim Taleb" },
  { quote: "The only way to win is to learn faster than anyone else.", author: "Nassim Taleb" },
  { quote: "Wind extinguishes a candle and energizes fire.", author: "Nassim Taleb" },
  { quote: "You are rich if money you refuse tastes better than money you accept.", author: "Nassim Taleb" },
  { quote: "Read books are far less valuable than unread ones.", author: "Nassim Taleb" },
  { quote: "The best way to verify that you are alive is by checking if you like variations.", author: "Nassim Taleb" },
  { quote: "A Stoic is someone who transforms fear into prudence, pain into transformation, mistakes into initiation.", author: "Nassim Taleb" },
  { quote: "Missing a train is only painful if you run after it.", author: "Nassim Taleb" },

  // Mohnish Pabrai (5)
  { quote: "The stock market is a no-called-strike game.", author: "Mohnish Pabrai" },
  { quote: "Invest in a few businesses that you understand well rather than many that you don't.", author: "Mohnish Pabrai" },
  { quote: "Heads I win, tails I don't lose much.", author: "Mohnish Pabrai" },
  { quote: "The key to investing is not assessing how much an industry is going to affect society, but rather determining the competitive advantage of any given company.", author: "Mohnish Pabrai" },
  { quote: "The difference between a good business and a bad business is that good businesses throw up one easy decision after another.", author: "Mohnish Pabrai" },

  // Joel Greenblatt (5)
  { quote: "Choosing individual stocks without any idea of what you're looking for is like running through a dynamite factory with a burning match.", author: "Joel Greenblatt" },
  { quote: "The secret to investing is to figure out the value of something – and then pay a lot less.", author: "Joel Greenblatt" },
  { quote: "Value investing works because it doesn't always work.", author: "Joel Greenblatt" },
  { quote: "Over the short term, Mr. Market acts like a wildly emotional guy who can buy or sell stocks at depressed or inflated prices.", author: "Joel Greenblatt" },
  { quote: "The magic formula works because it's simple and because it's based on buying good companies at bargain prices.", author: "Joel Greenblatt" },

  // Li Lu (5)
  { quote: "The best investment you can make is an investment in yourself.", author: "Li Lu" },
  { quote: "True investing is about paying less than something is worth.", author: "Li Lu" },
  { quote: "Great investment ideas are rare, and when they come, you have to act.", author: "Li Lu" },
  { quote: "Compounding is the royal road to wealth.", author: "Li Lu" },
  { quote: "The best businesses are those that earn high returns on capital and reinvest at similar rates.", author: "Li Lu" },

  // Other Investors & Economists (33)
  { quote: "In investing, what is comfortable is rarely profitable.", author: "Robert Arnott" },
  { quote: "The four most expensive words in the English language are 'this time it's different.'", author: "Sir John Templeton" },
  { quote: "Markets can remain irrational longer than you can remain solvent.", author: "John Maynard Keynes" },
  { quote: "The individual investor should act consistently as an investor and not as a speculator.", author: "Ben Graham" },
  { quote: "Wealth is not about having a lot of money; it's about having a lot of options.", author: "Chris Rock" },
  { quote: "The goal isn't more money. The goal is living life on your terms.", author: "Chris Brogan" },
  { quote: "It's not how much money you make, but how much money you keep.", author: "Robert Kiyosaki" },
  { quote: "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.", author: "Dave Ramsey" },
  { quote: "Money is a terrible master but an excellent servant.", author: "P.T. Barnum" },
  { quote: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau" },
  { quote: "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order.", author: "T.T. Munger" },
  { quote: "Do not save what is left after spending; instead spend what is left after saving.", author: "Warren Buffett" },
  { quote: "I will tell you how to become rich. Close the doors. Be fearful when others are greedy. Be greedy when others are fearful.", author: "Warren Buffett" },
  { quote: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { quote: "The investor's chief problem – and even his worst enemy – is likely to be himself.", author: "Benjamin Graham" },
  { quote: "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.", author: "Paul Samuelson" },
  { quote: "Returns matter a lot. It's our capital.", author: "Abigail Johnson" },
  { quote: "Compound interest is the eighth wonder of the world.", author: "Albert Einstein" },
  { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { quote: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", author: "Ayn Rand" },
  { quote: "Every once in a while, the market does something so stupid it takes your breath away.", author: "Jim Cramer" },
  { quote: "Bottoms in the investment world don't end with four-year lows; they end with 10- or 15-year lows.", author: "Jim Rogers" },
  { quote: "The key to making money in stocks is not to get scared out of them.", author: "Peter Lynch" },
  { quote: "The stock market is never obvious. It is designed to fool most of the people, most of the time.", author: "Jesse Livermore" },
  { quote: "Good investors gather information, put that information into current and historical context, then make sound decisions.", author: "Kenneth Fisher" },
  { quote: "The entrance strategy is actually more important than the exit strategy.", author: "Edward Lampert" },
  { quote: "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.", author: "Benjamin Franklin" },
  { quote: "Financial freedom is available to those who learn about it and work for it.", author: "Robert Kiyosaki" },
  { quote: "Success in investing doesn't correlate with IQ. What you need is the temperament to control urges.", author: "Warren Buffett" },
  { quote: "I'd compare stock pickers to astrologers, but I don't want to bad-mouth the astrologers.", author: "Eugene Fama" },
  { quote: "Wall Street makes its money on activity. You make your money on inactivity.", author: "Warren Buffett" },
  { quote: "The stock market is the story of cycles and of human behavior that is responsible for overreactions.", author: "Seth Klarman" },
  { quote: "A great business at a fair price is superior to a fair business at a great price.", author: "Charlie Munger" }
];

export default INVESTMENT_QUOTES;
