[
  {"Name":"USA Stocks","Code":"US","Country":"USA"},
  {"Name":"London Exchange","Code":"LSE","Country":"UK"},
  {"Name":"Toronto Exchange","Code":"TO","Country":"Canada"},
  {"Name":"NEO Exchange","Code":"NEO","Country":"Canada"},
  {"Name":"TSX Venture Exchange","Code":"V","Country":"Canada"},
  {"Name":"Berlin Exchange","Code":"BE","Country":"Germany"},
  {"Name":"Hamburg Exchange","Code":"HM","Country":"Germany"},
  {"Name":"XETRA Stock Exchange","Code":"XETRA","Country":"Germany"},
  {"Name":"Dusseldorf Exchange","Code":"DU","Country":"Germany"},
  {"Name":"Hanover Exchange","Code":"HA","Country":"Germany"},
  {"Name":"Munich Exchange","Code":"MU","Country":"Germany"},
  {"Name":"Stuttgart Exchange","Code":"STU","Country":"Germany"},
  {"Name":"Frankfurt Exchange","Code":"F","Country":"Germany"},
  {"Name":"Luxembourg Stock Exchange","Code":"LU","Country":"Luxembourg"},
  {"Name":"Vienna Exchange","Code":"VI","Country":"Austria"},
  {"Name":"Euronext Paris","Code":"PA","Country":"France"},
  {"Name":"Euronext Brussels","Code":"BR","Country":"Belgium"},
  {"Name":"Madrid Exchange","Code":"MC","Country":"Spain"},
  {"Name":"SIX Swiss Exchange","Code":"SW","Country":"Switzerland"},
  {"Name":"Euronext Lisbon","Code":"LS","Country":"Portugal"},
  {"Name":"Euronext Amsterdam","Code":"AS","Country":"Netherlands"},
  {"Name":"Iceland Exchange","Code":"IC","Country":"Iceland"},
  {"Name":"Irish Exchange","Code":"IR","Country":"Ireland"},
  {"Name":"Helsinki Exchange","Code":"HE","Country":"Finland"},
  {"Name":"Oslo Stock Exchange","Code":"OL","Country":"Norway"},
  {"Name": "Copenhagen Exchange", "Code": "CO", "Country": "Denmark"},
 {"Name": "Stockholm Exchange", "Code": "ST", "Country": "Sweden"},
 {"Name": "Australian Securities Exchange", "Code": "AU", "Country": "Australia"},
  {"Name": "Athens Exchange", "Code": "AT", "Country": "Greece"},
  {"Name": "London IL", "Code": "IL", "Country": "UK"}

]
